# Generated by Django 5.2.4 on 2025-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mod_delete_mods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='time_create',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
