# Generated by Django 5.2.4 on 2025-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_new_delete_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='created_at',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='created_at',
            new_name='time_create',
        ),
        migrations.AddField(
            model_name='mod',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='new',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
