# Generated by Django 5.2.4 on 2025-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_uploadedimage_rename_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default='Update 1.8.jpg', upload_to='main/images/', verbose_name='Изображение'),
        ),
    ]
