# Generated by Django 5.2.4 on 2025-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_uploadedimage_rename_name_comment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='image',
            field=models.ImageField(default='Update 1.8.jpg', upload_to='main/images/', verbose_name='Изображение'),
        ),
    ]
