# Generated by Django 5.2.4 on 2025-07-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='name',
        ),
    ]
