# Generated by Django 5.2.4 on 2025-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_title_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
